# Generated by Django 3.2 on 2022-05-17 15:17

from django.db import migrations
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='content',
            field=froala_editor.fields.FroalaField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
